name: build $ deploy my app spring boot
on:
   push:
     branches:
       - main
jobs:
  build-deploy:
    name: build and deploy spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup  jdk 17
        uses: actions/setup-java@v4
        width:
          distribution: 'corretto'
          java-version: 17

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name:  Build the application
        run:
              mvn clean 
              mvn -B package --file pom.xml




