name: build & deploy my app spring boot

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy Spring Boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn clean package --file pom.xml

      - name: Set image tag with date
        run: echo "TAG=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring_boot-app:${{ env.TAG }}
