name: build & deploy my app spring boot

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy Spring Boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn clean package --file pom.xml

      - name: build docker image
        uses: actions/buils-push-action@v2
        width:
            context: .
            dockerfile: Dockerfile
            push:  false
            tags: ${{ secrets.DOCKER_USERNAME }}/spring_boot-app:${{ env.TAG }}
      - name: login to docker  Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: push  to docker hub
        uses: actions/buils-push-action@v2
        width:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring_boot-app:${{ env.TAG }}
