name: build & deploy my app spring boot

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy Spring Boot app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn clean package --file pom.xml
